# Generated by Django 5.2.7 on 2025-12-20 16:05

from django.db import migrations

def copy_instructor_to_instructors(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        if course.instructor:
            course.instructors.add(course.instructor)

def reverse_copy_instructor_to_instructors(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        if course.instructors.count() > 0:
            course.instructor = course.instructors.first()
            course.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_instructors'),
    ]

    operations = [
        migrations.RunPython(copy_instructor_to_instructors, reverse_copy_instructor_to_instructors),
    ]
