# Generated by Django 5.2.7 on 2025-12-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_populate_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
