# Generated by Django 5.2.7 on 2025-12-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
    ]
