# Generated by Django 5.2.7 on 2025-12-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lessonprogress_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Plagiarism score (e.g., 0.00 to 100.00)', max_digits=5)),
                ('report_url', models.URLField(blank=True, help_text='URL to the detailed plagiarism report', max_length=500, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_plagiarized', models.BooleanField(default=False, help_text='Flag if the submission is considered plagiarized based on a threshold')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='courses.submission')),
            ],
            options={
                'ordering': ['-checked_at', 'score'],
            },
        ),
    ]
