# Generated by Django 5.2.7 on 2025-12-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    def create_initial_badges(apps, schema_editor):
        Badge = apps.get_model('gamification', 'Badge')
        
        badges = [
            {
                'name': 'Beginner',
                'slug': 'beginner',
                'description': 'Awarded for earning your first 50 points',
                'points_required': 50
            },
            {
                'name': 'Learner',
                'slug': 'learner',
                'description': 'Awarded for earning 100 points',
                'points_required': 100
            },
            {
                'name': 'Achiever',
                'slug': 'achiever',
                'description': 'Awarded for earning 250 points',
                'points_required': 250
            },
            {
                'name': 'Expert',
                'slug': 'expert',
                'description': 'Awarded for earning 500 points',
                'points_required': 500
            },
            {
                'name': 'Master',
                'slug': 'master',
                'description': 'Awarded for earning 1000 points',
                'points_required': 1000
            },
        ]
        
        for badge_data in badges:
            Badge.objects.get_or_create(
                slug=badge_data['slug'],
                defaults=badge_data
            )

    operations = [
        migrations.RunPython(create_initial_badges, reverse_code=migrations.RunPython.noop),
    ]
