# Generated by Django 5.2.7 on 2025-12-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_create_initial_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-points_required', 'name']},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-awarded_at'], 'unique_together': {('user', 'badge')}},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={'ordering': ['-total_points']},
        ),
    ]
