# Generated by Django 5.2.7 on 2025-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the quiz in minutes'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-17 15:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='submitted_at',
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-start_time']},
        ),
    ]
