# Generated by Django 5.2.7 on 2025-12-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quiz', '0002_auto_20251217_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='courses.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=1, help_text='Number of questions to be drawn from the bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.questionbank'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questionbank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_submissions', to='quiz.Question'),
        ),
    ]
