# Generated by Django 5.2.7 on 2025-12-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('essay', 'Essay')], default='multiple_choice', max_length=20),
        ),
        migrations.CreateModel(
            name='EssayQuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('ai_score', models.PositiveIntegerField(blank=True, null=True)),
                ('instructor_score', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to='quiz.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to='quiz.quizsubmission')),
            ],
        ),
    ]
