# Generated by Django 5.2.7 on 2025-12-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_essay_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EssayQuestionSubmission',
        ),
    ]
