# Generated by Django 5.2.7 on 2025-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_essayquestionsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='score',
            new_name='mcq_score',
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
