# Generated by Django 5.2.7 on 2025-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_score_to_mcq_score_and_add_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points_per_question',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded per correct answer'),
        ),
    ]
