# Generated by Django 5.2.7 on 2025-12-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peerreviewassignment',
            options={'ordering': ['due_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='peerreviewreview',
            options={'ordering': ['-reviewed_at'], 'unique_together': {('submission', 'reviewer')}},
        ),
        migrations.AlterModelOptions(
            name='peerreviewsubmission',
            options={'ordering': ['-submitted_at']},
        ),
    ]
