# Generated by Django 5.2.7 on 2025-12-17 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0, help_text='Students active in last 7 days')),
                ('average_completion_rate', models.FloatField(default=0.0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('forum_activity_count', models.IntegerField(default=0, help_text='Total forum posts/threads')),
                ('dropout_risk_count', models.IntegerField(default=0, help_text='Students at risk of dropping out')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='courses.course')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['course', '-calculated_at'], name='analytics_c_course__4383f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lesson_view', 'Lesson Viewed'), ('lesson_complete', 'Lesson Completed'), ('quiz_attempt', 'Quiz Attempted'), ('assignment_submit', 'Assignment Submitted'), ('forum_post', 'Forum Post Created'), ('chat_message', 'Chat Message Sent'), ('video_join', 'Video Session Joined')], max_length=20)),
                ('activity_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', '-timestamp'], name='analytics_s_student_d0e6ac_idx'), models.Index(fields=['course', '-timestamp'], name='analytics_s_course__ffbc25_idx'), models.Index(fields=['activity_type', '-timestamp'], name='analytics_s_activit_a01b5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_average', models.FloatField(default=0.0, help_text='Average quiz score percentage')),
                ('assignment_average', models.FloatField(default=0.0, help_text='Average assignment grade')),
                ('completion_rate', models.FloatField(default=0.0, help_text='Percentage of lessons completed')),
                ('engagement_score', models.FloatField(default=0.0, help_text='Overall engagement metric')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['student', 'course', '-snapshot_date'], name='analytics_s_student_c04485_idx')],
            },
        ),
    ]
