# Generated by Django 5.2.7 on 2025-12-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoconference', '0002_breakoutroom_videorecording_videosessionparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='meeting_url',
            field=models.CharField(blank=True, help_text='Unique internal identifier for the video session.', max_length=100, unique=True),
        ),
    ]
