# Generated by Django 5.2.7 on 2025-12-17 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonprogress'),
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('thread', 'Thread'), ('post', 'Post')], max_length=10)),
                ('emoji', models.CharField(help_text='Emoji character or code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='discussionthread',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='is_solution',
            field=models.BooleanField(default=False, help_text='Marked as solution by thread author or instructor'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['thread', 'created_at'], name='forum_discu_thread__befca5_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['course', '-updated_at'], name='forum_discu_course__6ea86d_idx'),
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.discussionpost'),
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.discussionthread'),
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['target_type', 'thread', 'emoji'], name='forum_forum_target__eb6c71_idx'),
        ),
        migrations.AddIndex(
            model_name='forumreaction',
            index=models.Index(fields=['target_type', 'post', 'emoji'], name='forum_forum_target__c4a0d3_idx'),
        ),
    ]
