# Generated by Django 5.2.7 on 2025-12-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumreaction_alter_discussionthread_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumreaction',
            options={'ordering': ['-created_at']},
        ),
    ]
