# Generated by Django 5.2.7 on 2025-12-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_is_read_messagereadreceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question a user might ask (or a representative phrase)')),
                ('answer_text', models.TextField(help_text="The chatbot's predefined answer")),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for better matching', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority means this answer is preferred if multiple match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='chat.chatbottopic')),
            ],
            options={
                'ordering': ['topic', '-priority', 'question_text'],
                'unique_together': {('topic', 'question_text')},
            },
        ),
    ]
